# Generated by Django 3.1.7 on 2022-04-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220416_1349'),
        ('project', '0002_auto_20220416_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companymodel'),
        ),
    ]
