# Generated by Django 3.1.7 on 2022-04-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='name',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
